Script shows how to list, update, remove installed modules.

Modules I have installed though not sure if I still use them all

Version    Name                                Repository           Description                                                                                                                                                                                                                                                                                             
-------    ----                                ----------           -----------                                                                                                                                                                                                                                                                                             
2.0.0.9    ActiveDirectoryTools                PSGallery            Custom tools for automating Active Directory management and setup. I've put these together to consolidate a number of scripts I regularly used.                                                                                                                                                         
6.3.1.0    AdmPwd.PS                           PSGallery            Provides cmdlets for configuration and usage of Local admin password management solution                                                                                                                                                                                                                
2.0.2.182  AzureAD                             PSGallery            Azure Active Directory V2 General Availability Module....                                                                                                                                                                                                                                               
2.0.2.183  AzureADPreview                      PSGallery            Azure Active Directory V2 Preview Module. ...                                                                                                                                                                                                                                                           
4.9        DSInternals                         PSGallery            The DSInternals PowerShell Module exposes several internal features of Active Directory and Azure Active Directory. These include FIDO2 and NGC key auditing, offline ntds.dit file manipulation, password auditing, DC recovery from IFM backups and password hash calculation....                     
3.2.0      ExchangeOnlineManagement            PSGallery            This is a General Availability (GA) release of the Exchange Online Powershell V3 module. Exchange Online cmdlets in this module are REST-backed and do not require Basic Authentication to be enabled in WinRM....                                                                                      
7.8.6      ImportExcel                         PSGallery            PowerShell module to import/export Excel spreadsheets, without Excel....                                                                                                                                                                                                                                
3.2.0      IntuneBackupAndRestore              PSGallery            PowerShell Module that queries Microsoft Graph, and allows for cross-tenant Backup & Restore actions of your Intune Configuration.                                                                                                                                                                      
2.5.0      Microsoft.Graph                     PSGallery            Microsoft Graph PowerShell module                                                                                                                                                                                                                                                                       
2.5.0      Microsoft.Graph.Applications        PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Authentication      PSGallery            Microsoft Graph PowerShell Authentication Module.                                                                                                                                                                                                                                                       
2.5.0      Microsoft.Graph.Bookings            PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Calendar            PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.ChangeNotifications PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.CloudCommunications PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Compliance          PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.CrossDeviceExper... PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.DeviceManagement    PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.DeviceManagement... PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.DeviceManagement... PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.DeviceManagement... PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
1.18.0     Microsoft.Graph.DeviceManagement... PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.DeviceManagement... PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Devices.CloudPrint  PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Devices.Corporat... PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Devices.ServiceA... PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.DirectoryObjects    PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Education           PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Files               PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Groups              PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Identity.Directo... PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Identity.Governance PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Identity.Partner    PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Identity.SignIns    PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
6.1907.1.0 Microsoft.Graph.Intune              PSGallery            PowerShell SDK for Microsoft Intune Graph API                                                                                                                                                                                                                                                           
2.5.0      Microsoft.Graph.Mail                PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Notes               PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.People              PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.PersonalContacts    PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Planner             PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Reports             PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.SchemaExtensions    PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Search              PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Security            PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Sites               PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Teams               PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Users               PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Users.Actions       PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
2.5.0      Microsoft.Graph.Users.Functions     PSGallery            Microsoft Graph PowerShell Cmdlets                                                                                                                                                                                                                                                                      
16.0.23... Microsoft.Online.SharePoint.Powe... PSGallery            Microsoft SharePoint Online Services Module for Windows PowerShell                                                                                                                                                                                                                                      
5.5.0      MicrosoftTeams                      PSGallery            Microsoft Teams cmdlets module for Windows PowerShell and PowerShell Core....                                                                                                                                                                                                                           
1.1.183.66 MSOnline                            PSGallery            Microsoft Azure Active Directory Module for Windows PowerShell                                                                                                                                                                                                                                          
1.5.12     O365ServiceCommunications           PSGallery            Gathers data regarding Office 365 Service Health from the Office 365 Service Communications API                                                                                                                                                                                                         
2.2.0      PnP.PowerShell                      PSGallery            Microsoft 365 Patterns and Practices PowerShell Cmdlets                                                                                                                                                                                                                                                 
2.1.1      PoShLog                             PSGallery            PoShLog is powershell logging module. ...                                                                                                                                                                                                                                                               
1.0.3      PS2HTMLTable                        PSGallery            Simplify Creating HTML Tables from an object or list and add styling to them on demand....                                                                                                                                                                                                              
2.5.2      PSLogging                           PSGallery            Creates and manages log files for your scripts.                                                                                                                                                                                                                                                         
1.21.0     PSScriptAnalyzer                    PSGallery            PSScriptAnalyzer provides script analysis and checks for potential code defects in the scripts by applying a group of built-in or customized rules on the scripts being analyzed.                                                                                                                       
2.2.0.3    PSWindowsUpdate                     PSGallery            This module contain cmdlets to manage Windows Update Client.                                                                                                                                                                                                                                            
0.0.180    PSWriteHTML                         PSGallery            PSWriteHTML is PowerShell Module to generate beautiful HTML reports, pages, emails without any knowledge of HTML, CSS or JavaScript. To get started basics PowerShell knowledge is required.                                                                                                            
1.4.1.2    ReportHTML                          PSGallery            A powerful module for creating HTML reports within PowerShell no HTML coding required.  For more details on what is possible, you can view the help file https://azurefieldnotesblog.blob.core.windows.net/wp-content/2017/06/Help-ReportHTML2.html ...                                                 
3.2.0      Send-MailKitMessage                 PSGallery            A replacement for PowerShell's obsolete Send-MailMessage implementing the Microsoft-recommended MailKit library.   
